# Generated by Django 5.1.3 on 2024-11-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrar_produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=100)),
                ('codigo_de_barra', models.IntegerField()),
                ('quantidade_total', models.IntegerField()),
                ('localizacao', models.IntegerField()),
            ],
        ),
    ]
