# Generated by Django 5.1.3 on 2024-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrar_produtos',
            name='codigo_de_barra',
            field=models.BigIntegerField(),
        ),
    ]
